name = "comet-example"
main = "src/index.ts"
compatibility_date = "2025-09-02"
compatibility_flags = [ 'nodejs_compat' ]

[[durable_objects.bindings]]
name = "MY_DURABLE_OBJECT"
class_name = "MyDurableObject"

[[migrations]]
tag = "v1"
new_classes = [ "MyDurableObject" ]
