name: Main

on:
  push:
    branches:
      - main

jobs:

  npm-publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    if: contains( join( github.event.commits.*.message, ', ' ), '[ci release]' )

    steps:
      - name: Checkout repository
        timeout-minutes: 3
        uses: actions/checkout@v4

      - name: Install pnpm
        timeout-minutes: 3
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install nodejs
        timeout-minutes: 3
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        timeout-minutes: 5
        run: pnpm install

      - name: Build package
        timeout-minutes: 3
        working-directory: packages/comet
        run: |
          pnpm run build

      - name: Publish to NPM
        id: npm-release
        uses: JS-DevTools/npm-publish@v3
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/comet

      - name: Tag latest commit
        if: steps.npm-release.outputs.type != ''
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh auth setup-git
          # Source: https://github.com/actions/checkout/pull/1707
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "v${{ steps.npm-release.outputs.version }}" -a -m "${{ github.event.commits[0].message }}"
          git push origin "v${{ steps.npm-release.outputs.version }}"

      - name: Create GitHub release
        if: steps.npm-release.outputs.type != ''
        run: |
          gh release create --generate-notes "v${{ steps.npm-release.outputs.version }}"
